### ISSUE TITLE
Fields that have a default value shouldn't be inferred as "type | undefined"

### ISSUE THREAD

**Issue by BahaaZidan** [plexinc/papr#209]
Currently, fields that have a default value shouldn't be inferred as "type | undefined".

Example code:
```ts
const userSchema = schema(
  {
    name: types.string({ required: true }),
    username: types.string({ required: true }),
    email: types.string({ required: true }),
    bio: types.string(),
    isDeactivated: types.boolean(),
  },
  {
    defaults: {
      isDeactivated: false,
    },
  }
);
```

The inferred type:
```ts
type UserDocument = {
    bio?: string | undefined;
    isDeactivated?: boolean | undefined;
} & {
    name: string;
    username: string;
    email: string;
    _id: ObjectId;
}
```

**Comment by avaly** [comment]
We had some discussions internally about this and I seem to have overlooked an edge case in my earlier comment:

During insertion it's true that these properties are using the default values.

However, since the properties are not defined as required in the schema, there's nothing stopping you from `$unset`-ing these properties after the document was created. The resulting document will still be valid according to the schema.

So we won't change the schema types for optional properties.

**Comment by BahaaZidan** [comment]
That makes sense. Thank you.
